[package]
name = "enumflags_derive"
version = "0.4.0"
authors = ["maik klein <maikklein@googlemail.com>"]
description = "Bitflags"
license = "MIT"
repository = "https://github.com/MaikKlein/enumflags"
keywords = ["enum", "bitflag", "flag", "bitflags"]

[dependencies]
syn = {version = "0.12.5", features = ["extra-traits"]}
quote = "0.4"
proc-macro2 = "0.2"

[lib]
proc-macro = true

[features]
default = []
nostd = []
